services:
  - type: web
    name: wellup
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOSTNAME
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        sync: false
